-- Run this once in the Supabase SQL editor. Google should be the only enabled
-- provider in Authentication > Providers.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  display_name text,
  tracked_nutrient text,
  tracked_nutrients text[] not null default '{}',
  avatar_url text,
  goal text not null check (goal in ('lose','maintain','gain','muscle','health')),
  height_feet smallint not null check (height_feet between 3 and 8),
  height_inches smallint not null check (height_inches between 0 and 11),
  weight_lbs numeric not null check (weight_lbs between 60 and 1000),
  age smallint not null check (age between 18 and 100),
  sex text not null check (sex in ('female','male')),
  activity_level numeric not null,
  daily_calories integer not null,
  protein_grams integer not null,
  carbs_grams integer not null,
  fat_grams integer not null,
  updated_at timestamptz not null default now()
);

-- Adds the customizable greeting name when upgrading an existing profiles table.
alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists tracked_nutrient text;
alter table public.profiles add column if not exists tracked_nutrients text[] not null default '{}';

-- Migrate the previous single nutrient choice into the new list once.
update public.profiles
set tracked_nutrients = array[tracked_nutrient]
where tracked_nutrient is not null and cardinality(tracked_nutrients) = 0;

alter table public.profiles enable row level security;
drop policy if exists "Users can read their own profile" on public.profiles;
drop policy if exists "Users can insert their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can read their own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- One row per user per day. Weekly, monthly, and yearly views are calculated
-- from these daily records so the same nutrition data is never duplicated.
create table if not exists public.daily_nutrition (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null default current_date,
  calories integer not null default 0 check (calories between 0 and 20000),
  protein_grams numeric(7,2) not null default 0 check (protein_grams between 0 and 2000),
  fiber_grams numeric(7,2) not null default 0 check (fiber_grams between 0 and 1000),
  carbs_grams numeric(7,2) not null default 0 check (carbs_grams between 0 and 5000),
  extra_nutrients jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, log_date)
);

alter table public.daily_nutrition add column if not exists extra_nutrients jsonb not null default '{}'::jsonb;

create index if not exists daily_nutrition_user_date_idx on public.daily_nutrition (user_id, log_date desc);
alter table public.daily_nutrition enable row level security;
drop policy if exists "Users can read their own nutrition" on public.daily_nutrition;
drop policy if exists "Users can insert their own nutrition" on public.daily_nutrition;
drop policy if exists "Users can update their own nutrition" on public.daily_nutrition;
drop policy if exists "Users can delete their own nutrition" on public.daily_nutrition;
create policy "Users can read their own nutrition" on public.daily_nutrition for select using (auth.uid() = user_id);
create policy "Users can insert their own nutrition" on public.daily_nutrition for insert with check (auth.uid() = user_id);
create policy "Users can update their own nutrition" on public.daily_nutrition for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own nutrition" on public.daily_nutrition for delete using (auth.uid() = user_id);

-- Reusable foods created from photographed nutrition labels.
create table if not exists public.saved_foods (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  serving_size text not null,
  calories integer not null default 0 check (calories between 0 and 20000),
  protein_grams numeric(7,2) not null default 0,
  fiber_grams numeric(7,2) not null default 0,
  carbs_grams numeric(7,2) not null default 0,
  image_url text,
  extra_nutrients jsonb not null default '[]'::jsonb,
  source_type text not null default 'custom' check (source_type in ('label', 'custom')),
  created_at timestamptz not null default now()
);

alter table public.saved_foods add column if not exists extra_nutrients jsonb not null default '[]'::jsonb;
alter table public.saved_foods add column if not exists source_type text not null default 'custom';
update public.saved_foods set source_type = 'label' where image_url is not null and source_type = 'custom';

alter table public.saved_foods enable row level security;
drop policy if exists "Users can read their own foods" on public.saved_foods;
drop policy if exists "Users can insert their own foods" on public.saved_foods;
drop policy if exists "Users can update their own foods" on public.saved_foods;
drop policy if exists "Users can delete their own foods" on public.saved_foods;
create policy "Users can read their own foods" on public.saved_foods for select using (auth.uid() = user_id);
create policy "Users can insert their own foods" on public.saved_foods for insert with check (auth.uid() = user_id);
create policy "Users can update their own foods" on public.saved_foods for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own foods" on public.saved_foods for delete using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('nutrition-labels', 'nutrition-labels', true)
on conflict (id) do update set public = true;

drop policy if exists "Users can upload their own label images" on storage.objects;
drop policy if exists "Users can update their own label images" on storage.objects;
drop policy if exists "Users can delete their own label images" on storage.objects;
create policy "Users can upload their own label images" on storage.objects for insert to authenticated
with check (bucket_id = 'nutrition-labels' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Users can update their own label images" on storage.objects for update to authenticated
using (bucket_id = 'nutrition-labels' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Users can delete their own label images" on storage.objects for delete to authenticated
using (bucket_id = 'nutrition-labels' and (storage.foldername(name))[1] = auth.uid()::text);

-- Itemized food diary. daily_nutrition remains the aggregate used by charts.
create table if not exists public.food_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null default current_date,
  saved_food_id bigint references public.saved_foods(id) on delete set null,
  food_name text not null,
  serving_size text not null default '1 serving',
  calories integer not null default 0,
  protein_grams numeric(7,2) not null default 0,
  fiber_grams numeric(7,2) not null default 0,
  carbs_grams numeric(7,2) not null default 0,
  image_url text,
  created_at timestamptz not null default now()
);

create index if not exists food_entries_user_date_idx on public.food_entries (user_id, entry_date desc);
alter table public.food_entries enable row level security;
drop policy if exists "Users can read their own food entries" on public.food_entries;
drop policy if exists "Users can insert their own food entries" on public.food_entries;
drop policy if exists "Users can update their own food entries" on public.food_entries;
drop policy if exists "Users can delete their own food entries" on public.food_entries;
create policy "Users can read their own food entries" on public.food_entries for select using (auth.uid() = user_id);
create policy "Users can insert their own food entries" on public.food_entries for insert with check (auth.uid() = user_id);
create policy "Users can update their own food entries" on public.food_entries for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own food entries" on public.food_entries for delete using (auth.uid() = user_id);
